---
- hosts: localhost
  become: true
  tasks:
    - name: Install systemd-networkd and systemd-resolved (if needed)
      pacman:
        name: systemd
        state: present

    - name: Create network configuration for systemd-networkd using ini_file
      ini_file:
        path: /etc/systemd/network/20-wired.network
        section: "{{ item.section }}"
        option: "{{ item.option }}"
        value: "{{ item.value }}"
      loop:
        - { section: 'Match', option: 'Name', value: 'enp*' }
        - { section: 'Network', option: 'DHCP', value: 'yes' }
        - { section: 'Network', option: 'Metric', value: '100' }

    - name: Enable and start systemd-networkd
      systemd:
        name: systemd-networkd
        enabled: true
        state: started

    - name: Enable and start systemd-resolved
      systemd:
        name: systemd-resolved
        enabled: true
        state: started

    - name: Symlink /etc/resolv.conf to systemd-resolved's stub resolver
      file:
        src: /run/systemd/resolve/stub-resolv.conf
        dest: /etc/resolv.conf
        state: link

    # - name: Configure systemd-resolved with custom DNS settings
    #   ini_file:
    #     path: /etc/systemd/resolved.conf
    #     section: 'Resolve'
    #     option: 'DNS'
    #     value: '8.8.8.8'

    - name: Configure fallback DNS
      ini_file:
        path: /etc/systemd/resolved.conf
        section: 'Resolve'
        option: 'FallbackDNS'
        value: '1.1.1.1'

    - name: Restart systemd-resolved to apply custom configuration
      systemd:
        name: systemd-resolved
        state: restarted

