---
- name: Setup environment for mkdocs using uv
  hosts: localhost
  vars:
    project_path: "{{ lookup('env', 'HOME') }}/.local/bin/mkdocs-venv"

  tasks:
    - name: Ensure uv is installed (via pipx)
      become: true
      pip:
        name: uv
        executable: pip3

    - name: Install python-uv if not already installed
      become: true
      package:
        name: python-uv
        state: present

    - name: Install direnv if not already installed
      become: true
      package:
        name: direnv
        state: present

    - name: Create project directory
      file:
        path: "{{ project_path }}"
        state: directory
        mode: "0755"

    - name: Install mkdocs dependencies with uv
      shell: |
        cd {{ project_path }}
        uv pip install .
      args:
        executable: /bin/bash

