[project]
name = "mkdocs-env"
version = "1.0.0"
dependencies = [
  "click",
  "future",
  "ghp-import",
  "importlib-metadata",
  "Jinja2",
  "joblib",
  "livereload",
  "lunr",
  "Markdown",
  "MarkupSafe",
  "mergedeep",
  "mkdocs",
  "mkdocs-material",
  "mkdocs-material-extensions",
  "mkdocs-pymdownx-material-extras",
  "nltk",
  "packaging",
  "Pygments",
  "pymdown-extensions",
  "pyparsing",
  "python-dateutil",
  "PyYAML",
  "pyyaml_env_tag",
  "regex",
  "six",
  "tornado",
  "tqdm",
  "watchdog",
  "zipp",
]
