-- neovim lua config
require('impatient')
require("user/core")
require("user/core_maps")
require("user/plugins")
require("user/cqconf")
require("user/plugins_conf")
require("user/plugins_maps")
require("user/lsp")
require("user/treesitter")
require("user/completion")
require("user/telescope")
require("user/style")
require("user/misc")
